package net.sakuramilk.TweakGS2.MultiBoot;

import android.content.Context;
import net.sakuramilk.TweakGS2.Common.SettingManager;

public class MultiBootSetting extends SettingManager {

    public static final String KEY_ROOT_PREF = "root_pref";
    public static final String KEY_ROM_SETTING_BASE = "rom_setting";

    public MultiBootSetting(Context context) {
        super(context);
    }

    @Override
    public void setOnBoot() {
        // TODO Autogenerated method stub
        
    }

    @Override
    public void setRecommend() {
        // TODO Autogenerated method stub
        
    }

    @Override
    public void reset() {
        // TODO Autogenerated method stub
        
    }

    
}
